FROM openjdk:17-jdk-slim AS build

WORKDIR /home
COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package -DskipTests

FROM openjdk:17-jdk-slim
COPY --from=build /home/target/*.jar product.jar
ENTRYPOINT ["java", "-jar", "product.jar"]