spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:postgresql://172.18.0.2/product
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
  cloud:
    config:
      enabled: false
    vault:
      authentication: token
      enabled: true
      kv:
        backend: product-service
        default-context: dev
        enabled: true
      token: ${VAULT_TOKEN}
      uri: http://localhost:8200/
  config:
    import: optional:vault://

vault_tester: ${vault_tester}

#  spring.cloud.config.enabled: false
#  spring.cloud.vault.enabled: true
#  spring.cloud.vault.uri: http://172.23.0.2:8200/
#  spring.cloud.vault.authentication: token
#  spring.cloud.vault.token: ${XX}
#
#  spring.cloud.vault.kv.enabled: true
#  spring.cloud.vault.kv.default-context: dev
#  spring.cloud.vault.kv.backend: product-service


# logging properties
logging:
  pattern:
    console: "%clr(TS=){faint}%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z', UTC}){faint} [%t] %clr(APP=){faint}%clr(${spring.application.name:null}){yellow} %clr(LEVEL=){faint}%clr(${LOG_LEVEL_PATTERN:%p}) %clr(CLASS=){faint}%clr(%logger{26}){cyan} %clr(TRACEID=){faint}%clr(%X{X-Correlation-Id:-null}){reverse} | %m%n%ex"


    
myk8s:
  user:
    user_name: Tyler
    last_name: Durden
    password: 1234